supply_analytics:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"       
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: DBT_ROLE
      warehouse: DBT_WH
      database: ANALYTICS_DEV
      schema: "dbt_{{ env_var('DBT_USER_SUFFIX', 'dev') }}"
      threads: 4
    ci:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: DBT_ROLE
      warehouse: DBT_WH
      database: ANALYTICS_CI
      schema: "{{ env_var('DBT_SCHEMA', 'ci') }}"
      threads: 4
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: DBT_ROLE
      warehouse: DBT_WH
      database: ANALYTICS_PROD
      schema: analytics
      threads: 4